name: Github Actions Maven Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
      - name : create a temporary artifact  folder
        run: mkdir Artifacts
      
      - name : Add artifacts to publish to the temp folder Artifacts folder
        run: |
          cd Artifacts
          echo 'Readme' > readme.html
          cd ..
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with :
          name: ArtifactsFolder
          path : target
