       ######Docker Image ######
name: Docker Workflow Create and Publish

on:
  workflow_call:
     inputs: 
        image_name:
         required: true
         type: string
        tag: 
         type: string
     secrets: 
      dock_username:
        required: true
      dock_password:
        required: true
        
jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nginx:$(date +%s)
      - name: Docker Login
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.dock_username }}
          password: ${{ secrets.dock_password }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: gursimrandock/java-maven
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run : echo "Process Completed"
